id: /subscriptions/e0783b50-4ca5-4059-83c1-524f39faa624/resourceGroups/rg-multimodaldemo/providers/Microsoft.App/containerapps/bankx-copilot
identity:
  type: None
location: East US
name: bankx-copilot
properties:
  configuration:
    activeRevisionsMode: Single
    dapr: null
    identitySettings: []
    ingress:
      additionalPortMappings: null
      allowInsecure: false
      clientCertificateMode: null
      corsPolicy: null
      customDomains: null
      exposedPort: 0
      external: true
      fqdn: bankx-copilot.bluemoss-7b03a6cd.eastus.azurecontainerapps.io
      ipSecurityRestrictions: null
      stickySessions: null
      targetPort: 8080
      traffic:
      - latestRevision: true
        weight: 100
      transport: Auto
    maxInactiveRevisions: 100
    registries:
    - identity: ''
      passwordSecretRef: multimodaldemoacroy6neblxi3zkqazurecrio-multimodaldemoacroy6neblxi3zkq
      server: multimodaldemoacroy6neblxi3zkq.azurecr.io
      username: multimodaldemoacroy6neblxi3zkq
    runtime: null
    secrets:
    - name: multimodaldemoacroy6neblxi3zkqazurecrio-multimodaldemoacroy6neblxi3zkq
    service: null
  customDomainVerificationId: B763D40B517987D4AEA45EB223B48B72CC661AD92FCC108DB8746583017346B0
  delegatedIdentities: []
  environmentId: /subscriptions/e0783b50-4ca5-4059-83c1-524f39faa624/resourceGroups/rg-multimodaldemo/providers/Microsoft.App/managedEnvironments/multimodaldemo-aca-env
  eventStreamEndpoint: https://eastus.azurecontainerapps.dev/subscriptions/e0783b50-4ca5-4059-83c1-524f39faa624/resourceGroups/rg-multimodaldemo/containerApps/bankx-copilot/eventstream
  latestReadyRevisionName: bankx-copilot--0000045
  latestRevisionFqdn: bankx-copilot--0000045.bluemoss-7b03a6cd.eastus.azurecontainerapps.io
  latestRevisionName: bankx-copilot--0000045
  managedEnvironmentId: /subscriptions/e0783b50-4ca5-4059-83c1-524f39faa624/resourceGroups/rg-multimodaldemo/providers/Microsoft.App/managedEnvironments/multimodaldemo-aca-env
  outboundIpAddresses:
  - 20.231.246.122
  - 20.231.246.54
  - 40.121.19.105
  - 40.121.18.246
  - 40.121.18.166
  - 40.121.18.60
  - 40.121.18.21
  - 40.121.18.44
  - 40.121.18.41
  - 40.121.18.248
  - 40.121.18.82
  - 40.121.19.108
  - 20.231.247.19
  - 40.121.19.125
  - 40.121.18.46
  - 40.117.125.130
  - 40.121.18.52
  - 40.121.18.33
  - 40.121.18.238
  - 40.121.19.2
  - 40.121.19.122
  - 40.121.19.19
  - 40.121.18.114
  - 20.231.246.253
  - 40.121.18.255
  - 40.121.18.164
  - 40.117.121.106
  - 40.121.18.27
  - 40.121.18.156
  - 40.121.18.117
  - 40.121.18.197
  - 40.121.18.133
  - 40.121.18.112
  - 40.121.18.106
  - 20.241.227.6
  - 40.121.19.89
  - 40.121.19.83
  - 40.121.18.131
  - 40.121.18.201
  - 40.121.18.170
  - 40.121.18.242
  - 13.92.130.42
  - 40.121.19.42
  - 40.121.18.73
  - 40.121.18.43
  - 20.241.226.169
  - 51.8.12.17
  - 4.156.180.142
  - 20.242.162.124
  - 40.121.19.74
  - 40.121.19.40
  - 40.121.18.62
  - 40.121.18.244
  - 20.127.248.50
  - 20.241.171.30
  - 20.169.229.88
  - 20.169.229.46
  - 20.169.229.29
  - 20.169.229.38
  - 20.169.229.62
  - 20.169.229.109
  - 20.169.229.92
  - 20.169.229.27
  - 20.169.229.51
  - 20.169.229.42
  - 20.241.172.248
  - 48.216.192.198
  - 40.90.243.232
  - 40.90.242.126
  - 135.237.112.47
  - 51.8.74.190
  - 4.157.197.142
  - 172.210.91.191
  - 172.210.90.42
  - 40.90.243.227
  - 40.90.243.72
  - 20.241.172.250
  - 52.234.235.220
  - 57.152.55.92
  - 172.212.36.156
  - 172.210.121.45
  - 172.214.2.208
  - 51.8.15.68
  - 172.210.90.119
  - 134.33.213.81
  - 128.203.83.220
  - 20.241.192.93
  - 20.246.203.138
  - 172.212.121.150
  - 172.171.186.158
  - 52.249.213.152
  - 74.179.213.114
  - 4.246.239.152
  - 4.156.216.65
  - 4.157.231.174
  - 172.171.168.136
  - 20.185.213.14
  - 20.246.203.140
  - 13.82.216.169
  - 13.82.216.172
  - 13.82.216.149
  - 52.170.33.171
  - 48.194.105.130
  provisioningState: Succeeded
  runningStatus: Running
  template:
    containers:
    - env:
      - name: PROFILE
        value: prod
      - name: PYTHONUNBUFFERED
        value: '1'
      - name: AZURE_AUTH_TENANT_ID
        value: ed6f4727-c993-424d-ad62-91492f3c1f41
      - name: AZURE_APP_CLIENT_ID
        value: c37e62a7-a62f-4ebf-a7c2-d6a3d318f76b
      - name: ACCOUNT_MCP_URL
        value: https://bankx-account-mcp.internal.bluemoss-7b03a6cd.eastus.azurecontainerapps.io
      - name: TRANSACTION_MCP_URL
        value: https://bankx-transaction-mcp.internal.bluemoss-7b03a6cd.eastus.azurecontainerapps.io
      - name: PAYMENT_MCP_URL
        value: https://bankx-payment-mcp.internal.bluemoss-7b03a6cd.eastus.azurecontainerapps.io
      - name: LIMITS_MCP_URL
        value: https://bankx-limits-mcp.internal.bluemoss-7b03a6cd.eastus.azurecontainerapps.io
      - name: CONTACTS_MCP_URL
        value: https://bankx-contacts-mcp.internal.bluemoss-7b03a6cd.eastus.azurecontainerapps.io
      - name: AUDIT_MCP_URL
        value: https://bankx-audit-mcp.internal.bluemoss-7b03a6cd.eastus.azurecontainerapps.io
      - name: PRODINFO_FAQ_MCP_URL
        value: http://bankx-prodinfo-faq-mcp:8076
      - name: AI_MONEY_COACH_MCP_URL
        value: http://bankx-ai-money-coach-mcp:8077
      - name: ESCALATION_COMMS_MCP_URL
        value: https://bankx-escalation-comms-mcp.internal.bluemoss-7b03a6cd.eastus.azurecontainerapps.io
      - name: FOUNDRY_PROJECT_ENDPOINT
        value: https://eastus.api.azureml.ms/agents/v1.0/subscriptions/e0783b50-4ca5-4059-83c1-524f39faa624/resourceGroups/rg-multimodaldemo/providers/Microsoft.MachineLearningServices/workspaces/banking-assistant-project
      - name: REVISION_REFRESH
        value: '20251203130230'
      - name: FOUNDRY_MODEL_DEPLOYMENT_NAME
        value: gpt-4o
      - name: AZURE_CLIENT_ID
        value: ed868161-d5e8-4314-beba-e74bb5e24c1d
      - name: AZURE_TENANT_ID
        value: c1e8c736-fd22-4d7b-a7a2-12c6f36ac388
      - name: AZURE_CLIENT_SECRET
        value: 5Hm8Q~eGGhX3mXNwjrU7luKNXnEQ~-XH1~Zjuc77
      - name: AZURE_OPENAI_ENDPOINT
        value: https://cog-oy6neblxi3zkq.openai.azure.com/
      - name: AZURE_OPENAI_API_KEY
        value: 663e82b434ee430f9fc4d1a1d424d729
      - name: AZURE_OPENAI_CHAT_DEPLOYMENT_NAME
        value: gpt-4o
      - name: AZURE_OPENAI_API_VERSION
        value: '2024-10-21'
      - name: AZURE_SEARCH_ENDPOINT
        value: https://gptkb-oy6neblxi3zkq.search.windows.net
      - name: AZURE_SEARCH_API_KEY
        value: 85RTnOwL0CGMrfbPf391AaUTxZ6mbQJ4gCBWh9eFR9AzSeCzg32e
      - name: AZURE_COSMOSDB_ENDPOINT
        value: https://bankx-conversations-prod.documents.azure.com:443/
      - name: AZURE_COSMOSDB_KEY
        value: CvFRnMuS924odXN6GCJk2ItuCUVWpUirTADUFOaZCjrvstIR6QkSBvHENn3z3NqiuqAqXjTPqdf5ACDbam12mw==
      - name: AZURE_COSMOSDB_DATABASE
        value: BankX
      - name: AZURE_COSMOSDB_CONTAINER_CONVERSATIONS
        value: Conversations
      - name: MCP_ACCOUNT_URL
        value: https://bankx-account-mcp.internal.proudgrass-1e0cb6ec.eastus.azurecontainerapps.io
      - name: MCP_TRANSACTION_URL
        value: https://bankx-transaction-mcp.internal.proudgrass-1e0cb6ec.eastus.azurecontainerapps.io
      - name: MCP_PAYMENT_URL
        value: https://bankx-payment-mcp.internal.proudgrass-1e0cb6ec.eastus.azurecontainerapps.io
      - name: MCP_LIMITS_URL
        value: https://bankx-limits-mcp.internal.proudgrass-1e0cb6ec.eastus.azurecontainerapps.io
      - name: MCP_CONTACTS_URL
        value: https://bankx-contacts-mcp.internal.proudgrass-1e0cb6ec.eastus.azurecontainerapps.io
      - name: MCP_AUDIT_URL
        value: https://bankx-audit-mcp.internal.proudgrass-1e0cb6ec.eastus.azurecontainerapps.io
      - name: MCP_PRODINFO_FAQ_URL
        value: https://bankx-prodinfo-faq-mcp.internal.proudgrass-1e0cb6ec.eastus.azurecontainerapps.io
      - name: MCP_AI_MONEY_COACH_URL
        value: https://bankx-ai-money-coach-mcp.internal.proudgrass-1e0cb6ec.eastus.azurecontainerapps.io
      - name: MCP_ESCALATION_COMMS_URL
        value: https://bankx-escalation-comms-mcp.internal.proudgrass-1e0cb6ec.eastus.azurecontainerapps.io
      - name: ESCALATION_COMMS_AGENT_ID
        value: asst_OZGs7bJTO2zK1YIy2xtVLisL
      - name: ACCOUNT_AGENT_ID
        value: asst_keTclryY22YcSXceBXzXeGmU
      - name: TRANSACTION_AGENT_ID
        value: asst_PQswtc01Lzubjc3yLATPQm8U
      - name: PAYMENT_AGENT_ID
        value: asst_ILaIlrPGtBWrWJDCpny0GqzH
      - name: PRODINFO_FAQ_AGENT_ID
        value: asst_XoEA7BkjnXaFpElLuNWD81E1
      - name: AI_MONEY_COACH_AGENT_ID
        value: asst_WJ9JomBttAWTu7JMwmrFRdZb
      - name: SUPERVISOR_AGENT_ID
        value: asst_n2vjRRiUPZAnewYc73GNvwFA
      - name: AZURE_OPENAI_MINI_DEPLOYMENT_NAME
        value: gpt-4.1-mini
      - name: AZURE_STORAGE_ACCOUNT
        value: stoy6neblxi3zkq
      - name: AZURE_STORAGE_CONTAINER
        value: content
      - name: AZURE_DOCUMENT_INTELLIGENCE_SERVICE
        value: cog-di-oy6neblxi3zkq
      - name: APPLICATIONINSIGHTS_CONNECTION_STRING
        value: InstrumentationKey=7a84f43c-e94d-40a7-b2f7-8255449bc781;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/;ApplicationId=8da6b665-c62e-4b99-8e16-265e99e46a71
      - name: ENABLE_OTEL
        value: 'true'
      - name: PRODINFO_FAQ_VECTOR_STORE_IDS
        value: vs_YTvUjvV0TuI8MSkLvKaXhg4q
      - name: RESTART_TRIGGER
        value: 20251203-231601
      - name: REDEPLOY_TS
        value: '2025-12-03T19:28:00Z'
      - name: USE_PREBUILT_AGENTS_ONLY
        value: 'true'
      image: multimodaldemoacroy6neblxi3zkq.azurecr.io/bankx-copilot:v20251205-conversations-fix-v2
      name: bankx-copilot
      resources:
        cpu: 1.0
        ephemeralStorage: 4Gi
        memory: 2Gi
      volumeMounts:
      - volumeName: conversations
        mountPath: /app/conversations
      - volumeName: dynamicdata
        mountPath: /app/dynamic_data
    initContainers: null
    revisionSuffix: ''
    scale:
      cooldownPeriod: 300
      maxReplicas: 3
      minReplicas: 1
      pollingInterval: 30
      rules: null
    serviceBinds: null
    terminationGracePeriodSeconds: null
    volumes:
    - name: conversations
      storageName: conversations
      storageType: AzureFile
    - name: dynamicdata
      storageName: dynamicdata
      storageType: AzureFile
  workloadProfileName: Consumption
resourceGroup: rg-multimodaldemo
systemData:
  createdAt: '2025-12-02T18:03:16.4721563'
  createdBy: Abhinav@metakaal.com
  createdByType: User
  lastModifiedAt: '2025-12-05T07:26:31.0600055'
  lastModifiedBy: Abhinav@metakaal.com
  lastModifiedByType: User
type: Microsoft.App/containerApps
